#!/usr/bin/php
<?php // console

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

/** @var \Interop\Container\ContainerInterface $container */
$container = require __DIR__ . '/container.php';
$application = new Application('RBC parser');
$config = $container->get('config');
$commands = $config->getConfig('console')['commands'];

foreach ($commands as $command) {
    $application->add($container->createInstance($command, $config));
}

$application->run();